logging:
  level:
    org:
      springframework: ERROR
      hibernate: ERROR
    com:
      cipitech: TRACE

server:
  port: 8081
  servlet:
    context-path: /blog

spring:
  profiles:
    active: global-exception, jdbc-data
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      file-size-threshold: 0B

  flyway:
    baseline-on-migrate: true


#  test:
#    database:
#      replace: none

uploadLocation: "C://logs//uploads"


